server {
    listen 80;
    server_name _;

    resolver 127.0.0.11 valid=10s ipv6=off;

    location /api/ {
        set $upstream_logger logger-client;
        proxy_pass http://$upstream_logger:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
